name: 'snowflake_migration'
version: '1.0.0'
config-version: 2

profile: 'snowflake_migration'

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  snowflake_migration:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    core:
      +materialized: table
      +schema: core
    marts:
      +materialized: table
      +schema: marts
