"""
FSP Analyst — Streamlit in Snowflake app over the MARTS layer.

Note: Cortex Analyst NL-to-SQL is *deferred* — the project's Snowflake
account is in AZURE_EASTUS, which Cortex Analyst does not yet support.
See docs/adr/0011-cortex-analyst-deferred.md. The semantic model and all
RBAC scaffolding stay in place, ready to swap the query path back to
Cortex when the region becomes supported.

This version gives analysts per-domain dashboards over the MARTS tables
plus a scoped SQL playground.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st
from snowflake.snowpark.context import get_active_session

st.set_page_config(page_title="FSP Analyst", page_icon=":bar_chart:", layout="wide")

session = get_active_session()

TENANTS = ["MAIN_BOOK", "INDIGO_INSURANCE", "HORIZON_ASSURANCE"]


# ---------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------

@st.cache_data(ttl=600, show_spinner=False)
def run_sql(query: str, _session_key: str = "default") -> pd.DataFrame:
    """Execute SQL on the active Snowpark session and return a DataFrame.

    The `_session_key` argument exists only to let callers bust the cache
    per-tab without making the cached queries carry the real session.
    """
    return session.sql(query).to_pandas()


def format_currency(n: float | None) -> str:
    if n is None or pd.isna(n):
        return "–"
    return f"R {n:,.0f}"


# ---------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------

st.title(":bar_chart: FSP Analyst")
st.caption(
    "Three domain dashboards over the MARTS layer plus a SQL playground. "
    "Every chart here is generated by a query against `ANALYTICS_DEV.MARTS.*`."
)

with st.expander(":information_source: About this app"):
    st.markdown(
        """
        **Why no natural-language chat?** The account region (`AZURE_EASTUS`)
        does not currently support Snowflake Cortex Analyst — see
        `docs/adr/0011-cortex-analyst-deferred.md`. The semantic model,
        RBAC grants, and Streamlit scaffolding are all Cortex-ready; a
        future version just swaps the query path in this file.
        """
    )

finance_tab, portfolio_tab, risk_tab, sql_tab = st.tabs(
    [":money_with_wings: Finance", ":chart_with_upwards_trend: Portfolio", ":shield: Risk", ":keyboard: SQL Playground"]
)

# ---------------------------------------------------------------------
# Finance: advisor commissions
# ---------------------------------------------------------------------

with finance_tab:
    st.header("Advisor commissions by month")

    col1, col2, col3 = st.columns([2, 2, 1])
    with col1:
        tenant = st.selectbox("Tenant", TENANTS, key="fin_tenant")
    with col2:
        category = st.selectbox("Category", ["INSURANCE", "INVESTMENT", "BOTH"], key="fin_cat")
    with col3:
        year = st.number_input("Year", min_value=2020, max_value=2030, value=2024, step=1, key="fin_year")

    cat_filter = (
        "" if category == "BOTH" else f"and commission_category = '{category}'"
    )

    totals_sql = f"""
        select
            to_char(year_month, 'YYYY-MM') as month,
            sum(commission_net_total) as net_total,
            sum(commission_gross_total) as gross_total,
            sum(commission_count) as commission_count
        from ANALYTICS_DEV.MARTS.FINANCE_ADVISOR_COMMISSIONS_MONTHLY
        where company = '{tenant}' and year = {int(year)} {cat_filter}
        group by 1
        order by 1
    """
    totals = run_sql(totals_sql, _session_key=f"fin_totals_{tenant}_{category}_{year}")

    if totals.empty:
        st.info(f"No commissions for {tenant} / {category} / {year}.")
    else:
        c1, c2, c3 = st.columns(3)
        c1.metric("Total net commissions", format_currency(totals["NET_TOTAL"].sum()))
        c2.metric("Total gross commissions", format_currency(totals["GROSS_TOTAL"].sum()))
        c3.metric("Commissions paid out", f"{int(totals['COMMISSION_COUNT'].sum()):,}")

        st.line_chart(totals.set_index("MONTH")[["NET_TOTAL", "GROSS_TOTAL"]])

    st.subheader(f"Top 10 advisors in {int(year)}")
    top_sql = f"""
        select advisor_identifier,
               sum(commission_net_total) as net_total,
               sum(commission_count) as commission_count
        from ANALYTICS_DEV.MARTS.FINANCE_ADVISOR_COMMISSIONS_MONTHLY
        where company = '{tenant}' and year = {int(year)} {cat_filter}
        group by advisor_identifier
        order by net_total desc
        limit 10
    """
    st.dataframe(
        run_sql(top_sql, _session_key=f"fin_top_{tenant}_{category}_{year}"),
        use_container_width=True,
    )

# ---------------------------------------------------------------------
# Portfolio: AUM by fund
# ---------------------------------------------------------------------

with portfolio_tab:
    st.header("Assets under management by fund")

    col1, col2 = st.columns(2)
    with col1:
        tenant_p = st.selectbox("Tenant", TENANTS, key="port_tenant")
    with col2:
        fund_type = st.selectbox("Fund type", ["BOTH", "ETF", "UNIT_TRUST"], key="port_type")

    type_filter = "" if fund_type == "BOTH" else f"and fund_type = '{fund_type}'"

    trend_sql = f"""
        select to_char(year_month, 'YYYY-MM') as month,
               sum(aum_amount) as total_aum
        from ANALYTICS_DEV.MARTS.PORTFOLIO_AUM_MONTHLY
        where company = '{tenant_p}' {type_filter}
        group by 1 order by 1
    """
    trend = run_sql(trend_sql, _session_key=f"port_trend_{tenant_p}_{fund_type}")

    if trend.empty:
        st.info(f"No AUM data for {tenant_p} / {fund_type}.")
    else:
        latest = trend.iloc[-1]["TOTAL_AUM"]
        st.metric(f"Latest AUM ({trend.iloc[-1]['MONTH']})", format_currency(latest))
        st.line_chart(trend.set_index("MONTH")["TOTAL_AUM"])

    st.subheader("Top funds by latest-month AUM")
    latest_sql = f"""
        select fund_name, fund_type, jse_code, aum_amount, aum_mom_pct_change
        from ANALYTICS_DEV.MARTS.PORTFOLIO_AUM_MONTHLY
        where company = '{tenant_p}' {type_filter}
          and year_month = (
            select max(year_month)
            from ANALYTICS_DEV.MARTS.PORTFOLIO_AUM_MONTHLY
            where company = '{tenant_p}'
          )
        order by aum_amount desc
        limit 15
    """
    st.dataframe(
        run_sql(latest_sql, _session_key=f"port_latest_{tenant_p}_{fund_type}"),
        use_container_width=True,
    )

# ---------------------------------------------------------------------
# Risk: policies in force
# ---------------------------------------------------------------------

with risk_tab:
    st.header("Risk policy book")

    tenant_r = st.selectbox("Tenant", TENANTS + ["ALL"], key="risk_tenant")

    tenant_filter = "" if tenant_r == "ALL" else f"where company = '{tenant_r}'"

    summary_sql = f"""
        select
            policy_status,
            sum(policy_count) as policies,
            sum(annualised_premium) as annualised_premium
        from ANALYTICS_DEV.MARTS.RISK_POLICY_INFORCE
        {tenant_filter}
        group by policy_status
        order by policies desc
    """
    summary = run_sql(summary_sql, _session_key=f"risk_summary_{tenant_r}")

    if summary.empty:
        st.info("No policy data.")
    else:
        c1, c2, c3 = st.columns(3)
        total = int(summary["POLICIES"].sum())
        active = int(
            summary[summary["POLICY_STATUS"] == "Active"]["POLICIES"].sum()
        )
        annual = float(summary["ANNUALISED_PREMIUM"].sum())
        c1.metric("Total policies", f"{total:,}")
        c2.metric("Active", f"{active:,}", f"{active / max(total, 1):.1%} of book")
        c3.metric("Annualised premium", format_currency(annual))

        st.bar_chart(summary.set_index("POLICY_STATUS")["POLICIES"])
        st.dataframe(summary, use_container_width=True)

    st.subheader("Active-rate by smoker status and income bracket")
    breakdown_sql = f"""
        select smoker_status, income_bracket,
               sum(policy_count) as policies,
               avg(active_rate) as avg_active_rate
        from ANALYTICS_DEV.MARTS.RISK_POLICY_INFORCE
        {tenant_filter}
        group by smoker_status, income_bracket
        order by smoker_status, income_bracket
    """
    st.dataframe(
        run_sql(breakdown_sql, _session_key=f"risk_breakdown_{tenant_r}"),
        use_container_width=True,
    )

# ---------------------------------------------------------------------
# SQL playground
# ---------------------------------------------------------------------

with sql_tab:
    st.header("SQL playground")
    st.caption(
        "Any query you like, so long as it only reads from "
        "`ANALYTICS_DEV.MARTS.*` (caller's role is enforced by Snowflake)."
    )

    default_sql = (
        "select company, fund_name, year_month, aum_amount\n"
        "from ANALYTICS_DEV.MARTS.PORTFOLIO_AUM_MONTHLY\n"
        "where company = 'MAIN_BOOK'\n"
        "order by year_month desc, aum_amount desc\n"
        "limit 50;"
    )
    sql = st.text_area("SQL", value=default_sql, height=200)

    if st.button("Run"):
        try:
            with st.spinner("Running..."):
                df = session.sql(sql.rstrip(";\n ")).to_pandas()
            st.success(f"{len(df):,} rows")
            st.dataframe(df, use_container_width=True)
        except Exception as e:  # noqa: BLE001
            st.error(f"Query failed: {e}")
